### PR TITLE
Fix issues relating to warnings/alerts after edit

### LINKED ISSUE #126: [PE-D][Tester B] Spending limit alert shown incorrectly after editing an expense
When editing an expense such that the total expenditure for a category falls below the spending limit, the application still shows an alert message indicating that the limit has been exceeded.
Steps to Reproduce:
Add an expense that brings the total expenditure over the category limit.
Edit the expense to reduce the total expenditure below the limit.
Observe that the alert message still appears.
Expected Behavior: No alert should be shown if the total expenditure is within the limit after editing.
Actual Behavior: An alert is shown, incorrectly indicating that the limit has been exceeded.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cxc0418/ped#2

### LINKED ISSUE #150: [PE-D][Tester C] Can add negative spending limit
Doesnt give any warning

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rharwo/ped#1

### PR DESCRIPTION
**Pull request by Progresst-8**
Fix #150: add negative checks
Fix #126: Rewrote EditCommand execute method to be clearer. The messy code is probably the reason why the alerts/warnings were popping up even though they weren't supposed to.

### CODE REVIEW

File: src/main/java/wheresmymoney/category/CategoryTracker.java [hunk 1]
```diff
@@ -67,11 +67,15 @@ public void checkLimitOf(String category) throws WheresMyMoneyException {
         float currExpenditure = categoryData.getCurrExpenditure();
         float maxExpenditure = categoryData.getMaxExpenditure();
         if (categoryData.hasExceededLimit()) {
-            System.out.println("Alert! You have exceeded the spending limit of " + maxExpenditure +
-                    " for the category of " + category + ", with a total expenditure of " + currExpenditure + ". ");
+            System.out.println(
```
Comment (KHsienKit) [inline src/main/java/wheresmymoney/category/CategoryTracker.java:70]: Use Ui.displayMessage()

**Review by KHsienKit — CHANGES_REQUESTED** [review]

**Review by KHsienKit — APPROVED** [review]
Looks good
